In [ ]:
import numpy as np
import random as random

In [ ]:
# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
arr1_1 = np.arange(0, 10, 2)
arr1_2 = np.ones(9).reshape(3,3)
arr1_3 = np.array([7,7,7,7,7,7,7,7]).reshape(2,4)
arr1_4 = np.array([random.randint(10, 50) for _ in range(25)]).reshape(5, 5)

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 2 4 6 8]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[12 28 49 26 39]
 [28 31 27 42 37]]


In [ ]:
# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])


--- Task 2: Indexing and Slicing with Arrays ---
